/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MealsIndexImport } from './routes/meals.index'
import { Route as AdvancedIndexImport } from './routes/advanced.index'
import { Route as MealsMealIdImport } from './routes/meals.$mealId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MealsIndexRoute = MealsIndexImport.update({
  id: '/meals/',
  path: '/meals/',
  getParentRoute: () => rootRoute,
} as any)

const AdvancedIndexRoute = AdvancedIndexImport.update({
  id: '/advanced/',
  path: '/advanced/',
  getParentRoute: () => rootRoute,
} as any)

const MealsMealIdRoute = MealsMealIdImport.update({
  id: '/meals/$mealId',
  path: '/meals/$mealId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/meals/$mealId': {
      id: '/meals/$mealId'
      path: '/meals/$mealId'
      fullPath: '/meals/$mealId'
      preLoaderRoute: typeof MealsMealIdImport
      parentRoute: typeof rootRoute
    }
    '/advanced/': {
      id: '/advanced/'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedIndexImport
      parentRoute: typeof rootRoute
    }
    '/meals/': {
      id: '/meals/'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/advanced': typeof AdvancedIndexRoute
  '/meals': typeof MealsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/advanced': typeof AdvancedIndexRoute
  '/meals': typeof MealsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/advanced/': typeof AdvancedIndexRoute
  '/meals/': typeof MealsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meals/$mealId' | '/advanced' | '/meals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meals/$mealId' | '/advanced' | '/meals'
  id: '__root__' | '/' | '/meals/$mealId' | '/advanced/' | '/meals/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MealsMealIdRoute: typeof MealsMealIdRoute
  AdvancedIndexRoute: typeof AdvancedIndexRoute
  MealsIndexRoute: typeof MealsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MealsMealIdRoute: MealsMealIdRoute,
  AdvancedIndexRoute: AdvancedIndexRoute,
  MealsIndexRoute: MealsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/meals/$mealId",
        "/advanced/",
        "/meals/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/meals/$mealId": {
      "filePath": "meals.$mealId.tsx"
    },
    "/advanced/": {
      "filePath": "advanced.index.tsx"
    },
    "/meals/": {
      "filePath": "meals.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
